In [1]:
import requests
import re
import pandas as pd
import os
from datetime import date
import datetime
import json

In [2]:
df = pd.read_csv(os.path.join("data", "sc_weather.csv"))

In [3]:
df

,sensor_id,sensor_type,location,lat,lon,timestamp,date,time,hour,day,weekend,P1,P2,temp,tempmax,tempmin,conditions,weather
0,74650,SDS011,63169,46.042,14.592,2022-09-01 00:04:32,2022-09-01,0.075556,0,3,0,4.45,2.28,15.8,17.6,13.7,"Rain, Partially cloudy",humid
1,74650,SDS011,63169,46.042,14.592,2022-09-01 00:07:00,2022-09-01,0.116667,0,3,0,5.18,3.33,15.8,17.6,13.7,"Rain, Partially cloudy",humid
2,74650,SDS011,63169,46.042,14.592,2022-09-01 00:09:25,2022-09-01,0.156944,0,3,0,5.85,3.13,15.8,17.6,13.7,"Rain, Partially cloudy",humid
3,74650,SDS011,63169,46.042,14.592,2022-09-01 00:11:52,2022-09-01,0.197778,0,3,0,5.95,4.10,15.8,17.6,13.7,"Rain, Partially cloudy",humid
4,74650,SDS011,63169,46.042,14.592,2022-09-01 00:14:19,2022-09-01,0.238611,0,3,0,5.28,2.63,15.8,17.6,13.7,"Rain, Partially cloudy",humid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49141,67867,SDS011,54672,46.096,14.470,2022-10-25 23:49:16,2022-10-25,23.821111,23,1,0,29.60,7.72,13.1,17.0,9.0,"Rain, Partially cloudy",humid
49142,67867,SDS011,54672,46.096,14.470,2022-10-25 23:51:41,2022-10-25,23.861389,23,1,0,35.90,7.47,13.1,17.0,9.0,"Rain, Partially cloudy",humid
49143,67867,SDS011,54672,46.096,14.470,2022-10-25 23:54:07,2022-10-25,23.901944,23,1,0,71.68,9.40,13.1,17.0,9.0,"Rain, Partially cloudy",humid
49144,67867,SDS011,54672,46.096,14.470,2022-10-25 23:56:33,2022-10-25,23.942500,23,1,0,20.30,7.18,13.1,17.0,9.0,"Rain, Partially cloudy",humid
49145,67867,SDS011,54672,46.096,14.470,2022-10-25 23:59:00,2022-10-25,23.983333,23,1,0,53.75,8.70,13.1,17.0,9.0,"Rain, Partially cloudy",humid